version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing dependencies..."
      - echo "Logging in to Amazon ECR..."
      - aws --version  # Check AWS CLI version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 203070858919.dkr.ecr.eu-north-1.amazonaws.com
      - REPOSITORY_URI=203070858919.dkr.ecr.eu-north-1.amazonaws.com/aman/ecomm
      - IMAGE_TAG=build-$(date +%Y%m%d%H%M%S)
      - echo "Waiting for MySQL connection..."
      - until nc -z -v -w30 $DB_HOST 3306; do echo "Waiting for MySQL..."; sleep 5; done
      - echo "MySQL is reachable!"

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build started on `date`
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Writing image definitions file..."
      - DOCKER_CONTAINER_NAME=spring-java-backend
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
      - echo "Contents of imagedefinitions.json:"
      - cat imagedefinitions.json  

artifacts:
  files: 
    - imagedefinitions.json
    - target/ecomm_java_backend.jar
