version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecomm_dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    networks:
      - ecomm_network

  app:
    build: .
    container_name: ecomm_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ecomm_dev
      DB_USERNAME: admin
      DB_PASSWORD: admin123
    networks:
      - ecomm_network
    ports:
      - "5454:5454"

networks:
  ecomm_network:
